### ISSUE TITLE
Old version of Pangu7 suggested

### ISSUE THREAD

**Issue by twocows** [cfw-guide/ios.cfw.guide#130]
Hello,

Not sure if this is intentional, but the guide is suggesting an old version of Pangu7 (1.0-en instead of 1.2.1) for (at least) the iPhone 4 7.1(.2) section. The most recent version's available from archive.org at https://web.archive.org/web/20190602191004/http://dl.pangu.25pp.com/jb/Pangu_v1.2.1.exe

Additionally, as of 1.1.0 (according to https://www.theiphonewiki.com/wiki/Pangu), 25PP isn't even suggested unless the language is set to Chinese, so providing the more recent version might save users a step.

Sorry if the selection of the old version was intentional, feel free to ignore me if so.

**Comment by kawaiizenbo** [comment]
versions 1.1 and above do not work on windows due to dead servers.

**Comment by TheMasterOfMike** [comment]
See KawaiiZenbo’s comment
