### ISSUE TITLE
Please don't suggest sockH3lix

### ISSUE THREAD

**Issue by jack980517** [cfw-guide/ios.cfw.guide#152]
When I used sockH3lix on an iPad Air 1 on iOS 10.3.3, launching the MTerminal app would only print a line "Killed: 9". I can still SSH into it though. Switching to doubleh3lix fixed it.

**Comment by TheMasterOfMike** [comment]
1. MTerminal is trash, use NewTerm (works on my 5S 10.1.1)
2. Resolved in 493feef47c555262136d86d700c7a045688fcb9b
