### ISSUE TITLE
iPhone getting out of DFU when palera1n.sh is executed

### ISSUE THREAD

**Issue by nicoande** [cfw-guide/ios.cfw.guide#193]
Hello,

I wanted to jailbreak an iPhone 7 on IOS 15.5
Using a Mac (ARM) with Ventura 13.0.1
A USB-C to USB-A adapter was used. (Apple's official)

The iPhone got out of the DFU mode every time after creating the ramdisk.

**Comment by TheMasterOfMike** [comment]
This is not a support place, go to either the r/jailbreak discord or the palera1n discord.
