### ISSUE TITLE
appledb.dev

### ISSUE THREAD

**Issue by refriedfood** [cfw-guide/ios.cfw.guide#196]
It used to be a simple google chart of all the info you needed, simple and to the point: device, jailbreak name, ios number that's supported. Now it's a mess of unnecessary and convoluted junk of vague information and device types, without the core of what I actually need to know. Unless it's hidden in some super secret location or thinned out to make the site look as though it has more content, it no longer has what I need.

Can I have the better google docs back?

**Comment by TheMasterOfMike** [comment]
The Google Sheet had _so many fucking issues_ including (but not limited to):
- Constant maintenance issues (I remember there were months at a time where the chart could be outdated even after I asked multiple times about it)
- Easier to maintain (what sounds better to you: pinging somebody 500 times or submitting a PR in like 5 minutes)
- Inaccurate information (e.g. saying JailbreakMe Star supported the iPad 1 on 3.2.2 when it actually didn't)

Keep in mind that https://appledb.dev/ may contain a lot of extra information - AppleDB is not just about jailbreaking but is an Apple **D**ata**b**ase of sorts. If you want an easier chart to use, something like https://ios.cfw.guide/ (where you happened to submit this issue to) has a far more direct and reasonable-to-understand chart.
