### ISSUE TITLE
Update finding ECID on macOS

### ISSUE THREAD

**Issue by pnxl** [cfw-guide/ios.cfw.guide#229]
https://ios.cfw.guide/saving-blobs/#saving-blobs-all-devices

On this link, it says that you can find the ECID by going to the device summary page on Finder - that does not exist. A way to do so on a Mac would be to download the checkra1n app and then seeing your ECID there.

![Screenshot 2023-04-23 at 11 46 46](https://user-images.githubusercontent.com/66474423/233820383-6d62e605-1786-47b2-86fd-199260e3c5b2.png)

**Comment by RealKGB** [comment]
You can find your ECID in Finder - click on the listing that shows serial# or UDID. It will cycle through to show it in hex form.
