### ISSUE TITLE
iOS 9.3.5 points to non-existent `installing-kok3shi` guide

### ISSUE THREAD

**Issue by lifehackerhansol** [cfw-guide/ios.cfw.guide#236]
https://ios.cfw.guide/get-started/iPhone-4S.html, for example, goes to https://ios.cfw.guide/installing-kok3shi/, which is a 404. 

Randomly testing other devices known to have iOS 9.3.5 also show this behaviour.

**Comment by TheMasterOfMike** [comment]
resolved with https://github.com/littlebyteorg/appledb/commit/b34e6a0c262f39f6d68f6e44ff162193a8c0e101
