### ISSUE TITLE
Preferencees instead of Preferences in Sideloading Guide

### ISSUE THREAD

**Issue by TophattedWasTaken** [cfw-guide/ios.cfw.guide#242]
For AltStore, it says Preferencees instead of Preferences in step two
Would edit if I could, but I can not for the life of me figure out where the actual page to edit is as all the [edit links are broken ](https://github.com/cfw-guide/ios.cfw.guide/issues/240#issue-1835899691)

**Comment by TheMasterOfMike** [comment]
Resolved in https://github.com/cfw-guide/ios.cfw.guide/commit/801b5504f4dbb1ae715cc4f21e9712511c44d997

(This should also tell you where the file is as well for future reference)

**Comment by TophattedWasTaken** [comment]
Thank you! Now I'll know where to edit if I find more errors
