### ISSUE TITLE
Add trollstore SSH ramdisk tutorial

### ISSUE THREAD

**Issue by gamer191** [cfw-guide/ios.cfw.guide#251]
tutorial: https://github.com/opa334/TrollStore/blob/ea52074779f2e78ffabf1dc28a58550b123ce373/install_sshrd.md

I think it might be worthwhile to add this to ios.cfw.guide

**Comment by TheMasterOfMike** [comment]
this hasn't been updated for TrollStore 2.x in the first place, but to be honest imo jailbreaking with palera1n and installing TrollHelper and doing that is easier than this
