### ISSUE TITLE
Update totallynotspyware to tns-sockport

### ISSUE THREAD

**Issue by LuckyHeroes** [cfw-guide/ios.cfw.guide#271]
https://github.com/LukeZGD/tns-sockport

**Comment by gamer191** [comment]
> I recommend using [MeridianFix](https://github.com/LukeZGD/MeridianFix) instead because of issues with doubleH3lix

Regardless, the guide definitely needs to be updated from vanilla totallynotspyware

**Comment by TheMasterOfMike** [comment]
Done in https://github.com/cfw-guide/ios.cfw.guide/commit/6b43e34a7d7d607ee7a9194660fb99f78c56d109, re-tagging as Completed.
