### ISSUE TITLE
New method for ios 16.6.1 on arm64e

### ISSUE THREAD

**Issue by DavisThorne** [cfw-guide/ios.cfw.guide#272]
me and two guys in the discord came up with a method that seems pretty consistent, not sure where else to share so i’ll post here, feel free to close this issue or ignore just felt like sharing
(specs were iPhone 11; iOS 16.6.1) 

My Steps: (Lucian and FastTim did all the work this is what i did)

1: Install PureKFD (https://github.com/PureKFD/PureKFD/releases/tag/5.0beta_landa)
2: uninstall Tips
3: Reboot device
4: install Tips (don’t open it)
5 reboot (still don’t open tips)
6: Wait for a minute or two
7: Open PureKFD (don’t change any settings)
8: install trollstore helper (Developer > Install trollstore helper)
9: if it worked a pop up will appear saying installing
9.5: if the app crashes or device crashes retry opening PureKFD and installing trollstore
10: after installing hard reset your device
11: open the tips app and click install trollstore
11.5: if tips crashes open again uninstall trollstore then reinstall
12: after installing register tips as trollstore helper (i did this idk if it’s needed)
13: open trollstore go to setting and install persistence helper as Tips
14: success

**Comment by Mukul1127** [comment]
yes, then roothide bootstrap and serotonin jb

**Comment by TheMasterOfMike** [comment]
Serotonin isn't a full jailbreak.

As for the main point of the issue, this has been obsoleted by TrollStar in the first place.

**Comment by Mukul1127** [comment]
> Serotonin isn't a full jailbreak.
> 
> As for the main point of the issue, this has been obsoleted by TrollStar in the first place.

Serotonin is pretty close, just daemons and a couple of other things
