### ISSUE TITLE
New Jailbreak like tool for iOS 14.0-17.0 A8-A17 & M1+M2 - roothide Bootstrap

### ISSUE THREAD

**Issue by Mukul1127** [cfw-guide/ios.cfw.guide#279]
This project is promising and when you combine it with serotonin tool to enable springboard, it's almost like a normal jailbreak 

https://github.com/RootHide/Bootstrap

https://github.com/mineek/Serotonin

**Comment by TheMasterOfMike** [comment]
This is open to consideration for being added once Serotonin introduces rootless support, as of right now, no.

**Comment by Mukul1127** [comment]
> This is open to consideration for being added once Serotonin introduces rootless support, as of right now, no.

What do you mean by rootless, it is rootless but with a different root of /var/mobile/Containers/Shared/AppGroup/.jbroot-XXXXX

**Comment by Mukul1127** [comment]
<img width="414" alt="image" src="https://github.com/cfw-guide/ios.cfw.guide/assets/71291707/4cb613e0-248a-41ba-a2bf-0d8c2cac2894">

**Comment by gamer191** [comment]
@Mukul1127 you're sending MasterMike a screenshot of his own message😂

Even if it's been announced, Serotonin currently doesn't support the rootless (as opposed to roothide) architecture

**Comment by Mukul1127** [comment]
> @Mukul1127 you're sending MasterMike a screenshot of his own message😂
> 
> Even if it's been announced, Serotonin currently doesn't support the rootless (as opposed to roothide) architecture

Oops, yes I mean roothide Bootstrap is being updated for rootless, we might not even need serotonin maybe, I have no idea
