### ISSUE TITLE
Sideloadly transparency

### ISSUE THREAD

**Issue by ethanaobrien** [cfw-guide/ios.cfw.guide#324]
Every page that involves using sideloadly in the docs claims the following:

```
Sideloadly must make a request to its servers in
order to work with free developer accounts.
If you are not OK with this, you may use an
alternate Apple ID.
```

When, in reality, this only occurs if you have “Remote Anisette” enabled (which also required a Patreon subscription iirc)

Where is the disconnect? Is sideloadly not being transparent or are the docs leaving out the note on “Remote Anisette”

![image](https://github.com/user-attachments/assets/4b4b4d03-4a56-4546-ac2e-09b89a575519)

**Comment by gamer191** [comment]
Furthermore, none of the stuff that Sideloadly send to it's anisette servers would be considered private information (they literally get all those details when you visit their website to download Sideloadly)

(I'm assuming that the claim `Your Apple ID & Password is only sent to Apple servers` is accurate)

**Comment by ethanaobrien** [comment]
>(I'm assuming that the claim Your Apple ID & Password is only sent to Apple servers is accurate)

The claim is sideloadly claims to send nothing when using "Local Anisette", which I trust and believe from experience using in a VM with no internet. The documentation leaves this part out leading to me questioning what really goes on inside sideloadly.

Only "Remote Anisette" contacts their servers, and requires a patreon subscription.

**Comment by gamer191** [comment]
> Only "Remote Anisette" contacts their servers (according to them), and requires a patreon subscription.

From memory it doesn’t require a Patreon subscription. I’m not on my computer right now though (and I’ll forget to check later, so I may as well send this now)

**Comment by ethanaobrien** [comment]
![image](https://github.com/user-attachments/assets/3d8cacfc-6a82-40e7-892a-f42f0064b0ef)

**Comment by TheMasterOfMike** [comment]
Hi, apologies for the lack of response (been busy with some small things).

The sideloadly stuff is a bit of a relic from when Sideloadly doing remote stuff (with its older remote implementation) was the default method.

With local stuff, this isn't really necessary. This isn't going to be addressed immediately (I want to group this in with other, bigger changes) but this is something that is currently being cleaned up.

**Comment by TheMasterOfMike** [comment]
Resolved with https://github.com/cfw-guide/ios.cfw.guide/commit/3bce397cde17fd77c90170e5c4d54d92541155e8, closing
