### ISSUE TITLE
Using TrollInstallerX prevents apps from being updated

### ISSUE THREAD

**Issue by thatsprettygood** [cfw-guide/ios.cfw.guide#332]
https://github.com/alfiecg24/TrollInstallerX/issues/18
The issue was never solved without manual file system edits (and happened to me while following the guide)
It would be nice if there was a warning on the guide that this could occur.

**Comment by alfiecg24** [comment]
See my comment on the original issue: https://github.com/alfiecg24/TrollInstallerX/issues/18#issuecomment-2475602803.
