### ISSUE TITLE
Error on camera

### ISSUE THREAD

**Issue by wilwillyy** [cfw-guide/ios.cfw.guide#43]
after successfull Up to 14.3, on setting show notification on top "this phone is supervised and managed". then, i try to send image on whatsapp, instagram and many application but the camera blank. If i photo on camera, the photo can't save and gallery stuck. 
how to fix this? And sory my english bad.

My device : iphone 7+. 13.3 to 14.3

**Comment by The-Hacker894** [comment]
All questions regarding jailbreak help should be directed to the r/Jailbreak discord server at https://discord.gg/jb
