### ISSUE TITLE
For the iPhone 8 add an option for checkra1n on iOS 14.4.2 and just warn them that they will loose all forms of security. Some people like me who really want to jailbreak probably wouldn’t mind that drawback.

### ISSUE THREAD

**Issue by linusrg1** [cfw-guide/ios.cfw.guide#45]

**Comment by The-Hacker894** [comment]
We will not be adding checkra1n as an option for A11 devices on iOS 14 due to the huge security risk involved. iOS.CFW.Guide is intended to make jailbreaking easy, simple, and safe for the average user and adding A11 checkra1n on iOS 14 would go against this.

**Comment by TheMasterOfMike** [comment]
to further say something, sure, we *could* add a warning, but I doubt most people would actually read the warning

that, combined with what The-Hacker894 said, is why we have said multiple times we will not be adding A11 checkra1n to the guide as of now.

**Comment by linusrg1** [comment]
> We will not be adding checkra1n as an option for A11 devices on iOS 14 due to the huge security risk involved. iOS.CFW.Guide is intended to make jailbreaking easy, simple, and safe for the average user and adding A11 checkra1n on iOS 14 would go against this.

Well the 3ds guide is also supposed to be noob friendly yet they offer a more advanced hard mod option for users who wanna take that route, so I don’t really see an issue with it.

**Comment by TheMasterOfMike** [comment]
1. The guide has no formal association with NH, so comparing something from two different groups isn’t entirely fair
2. There are a couple differences to that, for example, with 3ds.hacks.guide, you have that, plus software options on all versions, plus NTRBoot.

As well, once it is done, it’s (to equivalence to this guide) untethered, only has to be done once, and doesn’t result in any net loss whenever entering jailbroken state (or in 3ds terms, CFW)

With this, it’s every time you enter jailbroken state you must take the security penalty while jailbroken, has to be done every time you reboot, and it’s the only option available to users.

**Comment by linusrg1** [comment]
> 1. The guide has no formal association with NH, so comparing something from two different groups isn’t entirely fair
> 2. There are a couple differences to that, for example, with 3ds.hacks.guide, you have that, plus software options on all versions, plus NTRBoot.
> 
> As well, once it is done, it’s (to equivalence to this guide) untethered, only has to be done once, and doesn’t result in any net loss whenever entering jailbroken state (or in 3ds terms, CFW)
> 
> With this, it’s every time you enter jailbroken state you must take the security penalty while jailbroken, has to be done every time you reboot, and it’s the only option available to users on 14.4+ (which is where we would recommend it anyways)

Well you are still technically lying to people who are on those versions.

**Comment by emiyl** [comment]
The checkra1n team didn't want to (afaik) release support for A11 iOS 14 and only did so because unofficial builds were circulating which allowed for it to work. As they didn't want users to use it, we won't recommend it either.

If the user really wants to jailbreak iOS 14 on A11, they can do their own research.

**Comment by linusrg1** [comment]
> The checkra1n team didn't want to (afaik) release support for A11 iOS 14 and only did so because unofficial builds were circulating which allowed for it to work. As they didn't want users to use it, we won't recommend it either.
> 
> If the user really wants to jailbreak iOS 14 on A11, they can do their own research.

How were unofficial builds able to be made if the program is closed source?

**Comment by emiyl** [comment]
By reverse engineering and patching the binary

**Comment by linusrg1** [comment]
> By reverse engineering and patching the binary

Ok makes sense. Well why not just say for advanced users it is possible but it will not be covered in this guide. As it not recommended by us or the checkra1n team.

**Comment by emiyl** [comment]
Because the guide isn't meant for advanced users

**Comment by linusrg1** [comment]
> Because the guide isn't meant for advanced users

Neither are other community hacking guides but at least they have the option. For example both the 3ds and wii u hacking communities want everything to be as noob friendly as possible. But they still have the option do install a hardmod or do coldboot haxchi both things that can brick your console. They have huge warnings on them and no one in either of those communities really recommend them but they still mention them because they do exist. And they want to lay out all the potential options for their users.

**Comment by emiyl** [comment]
We have thought it through already and we don't want to include it.
