### ISSUE TITLE
Revert b9268a9e1765dd1a0a58b2638ebf231ed61b963c

### ISSUE THREAD

**Issue by Diatrus** [cfw-guide/ios.cfw.guide#69]
All I get are emails complaining about issues after using beltuguese. Just use the regular script, especially since beltuguese is just a script running gui like the old futurerestore guis.

**Comment by dabezt31** [comment]
![image](https://user-images.githubusercontent.com/48022799/117545765-d6e1b600-b02f-11eb-8bc6-2394c1e4b7f0.png)
